# Additional configuration file to use for development
# bundle exec jekyll serve --config _config.yml,_config_dev.yml
environment:    "development"

# Your website URL (e.g. http://example.github.io or http://www.example.com)
# Used for Sitemap.xml and your RSS feed
url: ""

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

plugins:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea

collections:
  docs:
    output: true
  pages:
    output: true
    permalink: /:path/
  schede:
    output: true

iconsurl: "/assets/images/icons/"

popup:
  pratiche: "Un cruscotto riassume lo storico delle pratiche attivate, grazie allo scambio dati tra sistemi, i frontend di gestione pratica dei singoli enti comunicano lo stato pratica."
  preferiti: "Grazie ai servizi interoperabili si potranno ricevere avvisi e scadenze da più enti, le scelte dell’utente profilano i servizi a catalogo secondo le sue preferenze."
  forum: "Uno spazio di discussione sui temi trattati all’interno delle comunità tematiche, uno strumento di partecipazione e comunicazione per gli operatori delle PA."
  aggiornamento: "Una piattaforma di gestione condivisa dei dati del portale riferiti alle PA partecipanti consente di aggiornare le informazioni di propria competenza."

